### PR TITLE
Do not create partitions that are not to be retained

### PR DESCRIPTION
**Pull request by nicolagi**
I realize this requires tests and possibly other changes, but it's just a start to make the proposal from #649 more concrete.
I did try this and works for my use case.

### CODE REVIEW

**Comment by keithf4** [comment]
Thanks for the proposal! partman work is on a small break since the 5.1 release, but I'll definitely review this when I get back to it!

**Comment by keithf4** [comment]
Sorry for the delay in getting back to this. Any chance you could redo this PR against the `development` branch? I tried changing the target branch to development, but it's too far out of sync. 

Otherwise, if you don't mind this PR not being directly merged in, I can just incorporate the change into my next extension update file.

**Comment by nicolagi** [comment]
Keith Fiske ***@***.***> wrote:
> Sorry for the delay in getting back to this.

Absolutely no problem!

> Any chance you could redo this PR against the `development` branch? I tried changing the target branch to development, but it's too far out of sync. 

Okay, I cherry picked the original change and placed it on top of the development branch.

**Comment by keithf4** [comment]
Thanks! Will hopefully get back to partman more this month

**Pull request merged**
