### PR TITLE
Use [in docs] "format" instead of concatenation for relation names

### PR DESCRIPTION
**Pull request by vitaly-burovoy**
Also remove [from docs] unnecessary conversion "oid" columns to "regclass" type when searching in tables: regclass is converted back to the "oid" type for comparison (and to use indexes).

The best way to see changes is:
git diff --word-diff=color HEAD^..HEAD

### CODE REVIEW

**Comment by vitaly-burovoy** [comment]
One question for changed queries: I left DDL generation logic "AS IS", but do not understand one block:
```sql
to_char(to_timestamp(substring(c.relname from 10), 'YYYYMMDD'), 'YYYYMMDD')
```
https://github.com/pgpartman/pg_partman/blob/3427224b407a094a36c1a4a084d6a1e0ac407a78/doc/migrate_to_partman.md?plain=1#L134

It looks as no-op for me (could be replaced with just `substring(c.relname from 10)`).

Whether it is copy-paste error or it is intentional and has special behavior?

**Comment by keithf4** [comment]
> One question for changed queries: I left DDL generation logic "AS IS", but do not understand one block:
> 
> ```sql
> to_char(to_timestamp(substring(c.relname from 10), 'YYYYMMDD'), 'YYYYMMDD')
> ```
> 
> https://github.com/pgpartman/pg_partman/blob/3427224b407a094a36c1a4a084d6a1e0ac407a78/doc/migrate_to_partman.md?plain=1#L134
> 
> It looks as no-op for me (could be replaced with just `substring(c.relname from 10)`).
> 
> Whether it is copy-paste error or it is intentional and has special behavior?

So this was not a good example here since, yes, this would essentially be a no-op because both the old time pattern and the new one are the same. If instead the time pattern was `YYYY_MM_DD` or any other pattern that someone may have been using, you'd want to do the full conversion steps to ensure the new time suffix matches the actual time value of what the old one was. I'll try and update this with a better example that's not a no-op. Thanks!

**Comment by keithf4** [comment]
Pushed up a better example for this so it doesn't look like a no-op. Thanks again!
Also went and added some pre-commit hooks to automatically clean up whitespace.

**Comment by vitaly-burovoy** [comment]
Thank you!

**Pull request merged**
